require("dotenv").config();
const express=require("express"),cors=require("cors"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),multer=require("multer"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const app=express(),PORT=Number(process.env.PORT||10000),JWT_SECRET=process.env.JWT_SECRET||"dev-only-secret";
const DATA_DIR=path.join(__dirname,"..","data"),DB_FILE=path.join(DATA_DIR,"db.json"),UPLOAD_DIR=path.join(__dirname,"..","uploads");
fs.mkdirSync(DATA_DIR,{recursive:true});fs.mkdirSync(UPLOAD_DIR,{recursive:true});
const seed={users:[],products:[],promotions:[],brands:[],orders:[],notifications:[],messages:[],conversations:[],trades:[],paymentMethods:[
{id:"cash_on_delivery",name:"Paiement à la livraison",description:"Paie à la réception.",provider:"cash",logo:"cash",enabled:true,instructions:"Prépare le montant exact à la livraison."},
{id:"stripe",name:"Carte bancaire",description:"Paiement sécurisé par Stripe.",provider:"stripe",logo:"stripe",enabled:false,instructions:"Paiement en ligne sécurisé."},
{id:"paypal",name:"PayPal",description:"Paiement avec PayPal.",provider:"paypal",logo:"paypal",enabled:false,instructions:"Paiement via PayPal."}
],streamingPlans:[
{id:"netflix-basic",service:"netflix",name:"Basic",price:0,currency:"HTG",description:"Abonnement mensuel",enabled:true},
{id:"netflix-standard",service:"netflix",name:"Standard",price:0,currency:"HTG",description:"Abonnement mensuel",enabled:true},
{id:"netflix-premium",service:"netflix",name:"Premium",price:0,currency:"HTG",description:"Abonnement mensuel",enabled:true},
{id:"disney-standard",service:"disney",name:"Standard",price:0,currency:"HTG",description:"Abonnement mensuel",enabled:true}
],settings:{tradeEnabled:true,adminPhone:process.env.ADMIN_WHATSAPP||"509XXXXXXXX",notificationPreferences:{}},pushSubscriptions:[]};
function merge(a,b){for(const[k,v]of Object.entries(b||{})){if(Array.isArray(v))a[k]=v;else if(v&&typeof v==="object"&&a[k]&&typeof a[k]==="object"&&!Array.isArray(a[k]))a[k]=merge(a[k],v);else a[k]=v}return a}
function load(){try{return fs.existsSync(DB_FILE)?merge(structuredClone(seed),JSON.parse(fs.readFileSync(DB_FILE,"utf8"))):structuredClone(seed)}catch{return structuredClone(seed)}}
const db=load();function save(){const t=DB_FILE+".tmp";fs.writeFileSync(t,JSON.stringify(db,null,2));fs.renameSync(t,DB_FILE)}
function id(p=""){return p+crypto.randomUUID()}function now(){return new Date().toISOString()}function email(v){return String(v||"").trim().toLowerCase()}function num(v){return Number.isFinite(Number(v))?Number(v):0}
function safe(u){if(!u)return null;const{passwordHash,...x}=u;return x}
function token(u){return jwt.sign({sub:u.id,email:u.email,role:u.role,isAdmin:u.isAdmin},JWT_SECRET,{expiresIn:"30d"})}
function auth(req,res,next){const h=String(req.headers.authorization||"");if(!h.startsWith("Bearer "))return res.status(401).json({message:"Authentification requise."});try{const p=jwt.verify(h.slice(7),JWT_SECRET),u=db.users.find(x=>x.id===p.sub);if(!u)throw 0;req.user=u;next()}catch{return res.status(401).json({message:"Session expirée ou invalide."})}}
function admin(req,res,next){if(!req.user?.isAdmin&&!["admin","ADMIN","owner","OWNER","superadmin","SUPERADMIN"].includes(String(req.user?.role)))return res.status(403).json({message:"Accès administrateur refusé."});next()}
function optional(req,_res,next){const h=String(req.headers.authorization||"");if(h.startsWith("Bearer ")){try{const p=jwt.verify(h.slice(7),JWT_SECRET);req.user=db.users.find(x=>x.id===p.sub)||null}catch{}}next()}
async function ensureAdmin(){const e=email(process.env.ADMIN_EMAIL),p=String(process.env.ADMIN_PASSWORD||"");if(!e||!p){console.warn("ADMIN_EMAIL/ADMIN_PASSWORD non définis.");return}let u=db.users.find(x=>x.email===e);const h=await bcrypt.hash(p,12);if(!u){u={id:id("usr_"),name:process.env.ADMIN_NAME||"ZhuoMarket Admin",email:e,passwordHash:h,role:"admin",isAdmin:true,avatar:"",createdAt:now(),updatedAt:now()};db.users.push(u)}else{u.passwordHash=h;u.role="admin";u.isAdmin=true;u.updatedAt=now()}save()}
const origins=String(process.env.CORS_ORIGINS||"*").split(",").map(x=>x.trim()).filter(Boolean);
app.use(cors({origin:(o,cb)=>!o||origins.includes("*")||origins.includes(o)?cb(null,true):cb(new Error("CORS origin not allowed")),credentials:true}));
app.use(express.json({limit:"2mb"}));app.use(express.urlencoded({extended:true,limit:"2mb"}));app.use("/uploads",express.static(UPLOAD_DIR));

const storage=multer.diskStorage({destination:(_r,_f,cb)=>cb(null,UPLOAD_DIR),filename:(_r,f,cb)=>{const ext=path.extname(f.originalname||"").toLowerCase()||".jpg";cb(null,Date.now()+"-"+crypto.randomBytes(6).toString("hex")+ext)}});
const upload=multer({storage,limits:{fileSize:8*1024*1024,files:1},fileFilter:(_r,f,cb)=>/^image\/(jpeg|png|webp|gif)$/i.test(f.mimetype)?cb(null,true):cb(new Error("Format image non supporté."))});

app.get("/api/health",(_r,s)=>s.json({ok:true,service:"zhuomarket-backend",time:now()}));

// Auth
app.post("/api/auth/register",async(req,res)=>{const b=req.body||{},n=String(b.name||"").trim(),e=email(b.email),p=String(b.password||"");if(!n||!e||p.length<6)return res.status(400).json({message:"Nom, email et mot de passe valide requis."});if(db.users.some(x=>x.email===e))return res.status(409).json({message:"Cet email existe déjà."});const u={id:id("usr_"),name:n,email:e,passwordHash:await bcrypt.hash(p,12),role:"customer",isAdmin:false,avatar:"",wishlist:[],settings:{},createdAt:now(),updatedAt:now()};db.users.push(u);save();res.status(201).json({token:token(u),user:safe(u)})});
app.post("/api/auth/login",async(req,res)=>{const b=req.body||{},u=db.users.find(x=>x.email===email(b.email));if(!u||!(await bcrypt.compare(String(b.password||""),u.passwordHash)))return res.status(401).json({message:"Email ou mot de passe incorrect."});res.json({token:token(u),user:safe(u)})});
app.get("/api/auth/me",auth,(req,res)=>res.json({user:safe(req.user)}));app.patch("/api/auth/me",auth,(req,res)=>{if(req.body.avatar!==undefined)req.user.avatar=String(req.body.avatar||"");if(req.body.name!==undefined)req.user.name=String(req.body.name||req.user.name);req.user.updatedAt=now();save();res.json({user:safe(req.user)})});
app.post("/api/auth/logout",auth,(_r,s)=>s.json({ok:true}));app.post("/api/auth/refresh",auth,(req,res)=>res.json({token:token(req.user)}));

// Catalog
app.get("/api/products",(req,res)=>{let a=db.products;if(String(req.query.available)==="true")a=a.filter(p=>Number(p.stock||0)>0&&p.status!=="paused");res.json({products:a})});
function productBody(b,p){return Object.assign(p||{}, {brand:String(b.brand||p?.brand||"").trim(),model:String(b.model||p?.model||"").trim(),image:String(b.image??p?.image??""),images:Array.isArray(b.images)?b.images.slice(0,10):(p?.images||[]),price:num(b.price??p?.price),currency:String(b.currency??p?.currency??"USD").toUpperCase()==="HTG"?"HTG":"USD",oldPrice:num(b.oldPrice??p?.oldPrice),discount:num(b.discount??p?.discount),stock:Math.max(0,Number(b.stock??p?.stock??0)),storage:Array.isArray(b.storage)?b.storage:(p?.storage||[]),colors:Array.isArray(b.colors)?b.colors:(p?.colors||[]),specifications:b.specifications||p?.specifications||{},description:String(b.description??p?.description??""),tradeEnabled:b.tradeEnabled!==false,status:b.status||p?.status||"published",updatedAt:now()})}
app.post("/api/products",auth,admin,(req,res)=>{const p=productBody(req.body||{}, {id:id("prd_"),createdAt:now()});if(!p.brand||!p.model||p.price<=0)return res.status(400).json({message:"Marque, modèle et prix sont obligatoires."});if(!p.image&&p.images[0])p.image=p.images[0];db.products.push(p);save();res.status(201).json({product:p})});
app.put("/api/products/:id",auth,admin,(req,res)=>{const p=db.products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({message:"Produit introuvable."});productBody(req.body||{},p);if(!p.image&&p.images[0])p.image=p.images[0];save();res.json({product:p})});
app.patch("/api/products/:id",auth,admin,(req,res)=>{const p=db.products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({message:"Produit introuvable."});Object.assign(p,req.body||{},{id:p.id,updatedAt:now()});save();res.json({product:p})});
app.delete("/api/products/:id",auth,admin,(req,res)=>{const n=db.products.length;db.products=db.products.filter(x=>x.id!==req.params.id);if(n===db.products.length)return res.status(404).json({message:"Produit introuvable."});db.promotions=db.promotions.filter(x=>x.productId!==req.params.id);save();res.json({ok:true})});

app.get("/api/promotions",(req,res)=>{let a=db.promotions;if(req.query.status)a=a.filter(x=>x.status===req.query.status);res.json({promotions:a})});
function promo(req,res){const b=req.body||{},p=db.promotions.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({message:"Promotion introuvable."});Object.assign(p,b,{id:p.id,updatedAt:now()});save();res.json({promotion:p})}
app.post("/api/promotions",auth,admin,(req,res)=>{const b=req.body||{},p={id:id("pro_"),productId:b.productId||null,title:String(b.title||""),image:String(b.image||""),images:Array.isArray(b.images)?b.images.slice(0,10):[],description:String(b.description||""),discount:num(b.discount),price:num(b.price),oldPrice:num(b.oldPrice),startDate:b.startDate||"",endDate:b.endDate||"",status:b.status||"published",createdAt:now(),updatedAt:now()};if(!p.image&&p.images[0])p.image=p.images[0];db.promotions.push(p);save();res.status(201).json({promotion:p})});
app.put("/api/promotions/:id",auth,admin,promo);app.patch("/api/promotions/:id",auth,admin,promo);app.delete("/api/promotions/:id",auth,admin,(req,res)=>{const n=db.promotions.length;db.promotions=db.promotions.filter(x=>x.id!==req.params.id);if(n===db.promotions.length)return res.status(404).json({message:"Promotion introuvable."});save();res.json({ok:true})});
app.get("/api/brands",(_r,s)=>s.json({brands:db.brands}));

// Upload
app.post("/api/uploads",auth,(req,res,next)=>upload.single("image")(req,res,e=>{if(e)return next(e);if(!req.file)return res.status(400).json({message:"Aucune image reçue."});const base=String(process.env.PUBLIC_BASE_URL||"").replace(/\/$/,"")||`http://localhost:${PORT}`,url=base+"/uploads/"+encodeURIComponent(req.file.filename);res.status(201).json({url,imageUrl:url,image:url,fileUrl:url,path:url})}));

// Orders
app.get("/api/orders",auth,(req,res)=>res.json({orders:db.orders.filter(o=>o.userId===req.user.id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}));
app.get("/api/orders/:id",auth,(req,res)=>{const o=db.orders.find(x=>x.id===req.params.id&&(x.userId===req.user.id||req.user.isAdmin));if(!o)return res.status(404).json({message:"Commande introuvable."});res.json({order:o})});
app.post("/api/orders",auth,(req,res)=>{const b=req.body||{},o={id:id("ord_"),userId:req.user.id,items:Array.isArray(b.items)?b.items:[],customer:b.customer||{},paymentMethod:String(b.paymentMethod||"cash_on_delivery"),total:num(b.total),status:"pending",paymentStatus:"pending",createdAt:now(),updatedAt:now()};if(b.serviceOrder)o.serviceOrder=b.serviceOrder;db.orders.push(o);for(const it of o.items){const p=db.products.find(x=>x.id===it.id||x.id===it.productId);if(p)p.stock=Math.max(0,Number(p.stock||0)-Math.max(1,Number(it.quantity||it.qty||1)))}db.notifications.push({id:id("not_"),userId:req.user.id,type:"order",title:"Commande reçue",message:`Commande #${o.id} reçue.`,read:false,createdAt:now()});save();res.status(201).json({order:o})});
app.patch("/api/orders/:id/status",auth,admin,(req,res)=>{const o=db.orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({message:"Commande introuvable."});o.status=String(req.body.status||"pending");o.updatedAt=now();db.notifications.push({id:id("not_"),userId:o.userId,type:"order_update",title:"Commande mise à jour",message:`Ta commande #${o.id} est maintenant: ${o.status}.`,read:false,createdAt:now()});save();res.json({order:o})});

// Notifications/user-state
app.get("/api/notifications",auth,(req,res)=>{const a=db.notifications.filter(n=>n.userId===req.user.id).sort((x,y)=>String(y.createdAt).localeCompare(String(x.createdAt)));res.json({notifications:a,unread:a.filter(x=>!x.read).length})});
app.post("/api/notifications",auth,(req,res)=>{const b=req.body||{},n={id:id("not_"),userId:req.user.id,type:b.type||"general",severity:b.severity||"normal",title:b.title||"ZhuoMarket",message:b.message||b.body||"",read:false,createdAt:now()};db.notifications.push(n);save();res.status(201).json({notification:n})});
app.get("/api/notification-preferences",auth,(req,res)=>res.json(db.settings.notificationPreferences[req.user.id]||{order_updates:true,payment_updates:true,messages:true,promotions:true,security:true,reminder_minutes:10}));
app.patch("/api/notification-preferences",auth,(req,res)=>{db.settings.notificationPreferences[req.user.id]=req.body||{};save();res.json({preferences:db.settings.notificationPreferences[req.user.id]})});
app.get("/api/user-state",auth,(req,res)=>res.json({user:safe(req.user),wishlist:req.user.wishlist||[],settings:req.user.settings||{}}));
app.patch("/api/user-state",auth,(req,res)=>{if(Array.isArray(req.body.wishlist))req.user.wishlist=req.body.wishlist;if(req.body.settings)req.user.settings=req.body.settings;save();res.json({user:safe(req.user),wishlist:req.user.wishlist||[],settings:req.user.settings||{}})});

// Trade
app.get("/api/trades",auth,(req,res)=>res.json({trades:db.trades.filter(x=>x.userId===req.user.id)}));
app.post("/api/trades",auth,(req,res)=>{const b=req.body||{},t={id:id("trd_"),userId:req.user.id,device:b.device||"",storage:b.storage||"",condition:b.condition||"",wantedProductId:b.wantedProductId||null,message:b.message||"",status:"pending",createdAt:now()};db.trades.push(t);save();res.status(201).json({trade:t})});

// Customer support
function conv(uid){let c=db.conversations.find(x=>x.userId===uid);if(!c){c={id:id("conv_"),userId:uid,createdAt:now(),updatedAt:now()};db.conversations.push(c)}return c}
app.get("/api/messages",auth,(req,res)=>{const c=conv(req.user.id),a=db.messages.filter(m=>m.conversationId===c.id).sort((x,y)=>String(x.createdAt).localeCompare(String(y.createdAt)));res.json({conversationId:c.id,messages:a})});
app.post("/api/messages",auth,(req,res)=>{const c=conv(req.user.id),b=req.body||{},text=String(b.message||"").trim();if(!text)return res.status(400).json({message:"Message vide."});const m={id:id("msg_"),conversationId:c.id,userId:req.user.id,senderId:req.user.id,senderRole:"customer",message:text,severity:b.severity||"normal",urgent:!!b.urgent,source:b.source||"support",createdAt:now(),readByAdmin:false};db.messages.push(m);c.updatedAt=now();save();res.status(201).json({message:m,conversationId:c.id})});

// Chatbot
app.post("/api/chatbot",auth,async(req,res)=>{const message=String(req.body?.message||"").trim();if(!message)return res.status(400).json({message:"Message vide."});let reply="Je peux t'aider avec les produits, commandes, paiements et le support ZhuoMarket.",needsAdmin=/admin|humain|urgent|réclamation|reclamation|problème|probleme/i.test(message);if(process.env.OPENAI_API_KEY){try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-4.1-mini",input:`Tu es le support ZhuoMarket. Réponds brièvement en français ou créole haïtien selon le message. Ne demande jamais de mot de passe ni de secret. Utilisateur: ${message}`})}),d=await r.json(),t=d.output?.flatMap(x=>x.content||[]).find(x=>x.type==="output_text")?.text;if(t)reply=t}catch{}}let conversationId=null;if(needsAdmin){const c=conv(req.user.id);conversationId=c.id;db.messages.push({id:id("msg_"),conversationId:c.id,userId:req.user.id,senderId:"bot",senderRole:"bot",message:`Résumé support: ${message}`,severity:"high",urgent:true,source:"chatbot",createdAt:now(),readByAdmin:false});c.updatedAt=now();save()}res.json({reply,needsAdmin,conversationId,severity:needsAdmin?"high":"normal"})});

// Payment methods
app.get("/api/payment-methods",(_r,s)=>s.json({paymentMethods:db.paymentMethods}));
app.get("/api/admin/payment-methods",auth,admin,(_r,s)=>s.json({paymentMethods:db.paymentMethods}));
app.post("/api/admin/payment-methods",auth,admin,(req,res)=>{const b=req.body||{},p={id:id("pm_"),name:String(b.name||"Méthode"),description:String(b.description||""),provider:String(b.provider||"cash"),logo:b.logo||b.provider||"cash",instructions:String(b.instructions||""),enabled:b.enabled!==false};db.paymentMethods.push(p);save();res.status(201).json({paymentMethod:p})});
app.patch("/api/admin/payment-methods/:id",auth,admin,(req,res)=>{const p=db.paymentMethods.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({message:"Méthode introuvable."});Object.assign(p,req.body||{},{id:p.id});save();res.json({paymentMethod:p})});
app.delete("/api/admin/payment-methods/:id",auth,admin,(req,res)=>{db.paymentMethods=db.paymentMethods.filter(x=>x.id!==req.params.id);save();res.json({ok:true})});
app.post("/api/payments/manual/confirm",auth,(req,res)=>{const o=db.orders.find(x=>x.id===req.body?.orderId&&x.userId===req.user.id);if(!o)return res.status(404).json({message:"Commande introuvable."});o.paymentStatus="pending_verification";o.paymentReference=String(req.body.reference||"");save();res.json({ok:true,order:o})});

// Stripe
app.post("/api/payments/stripe/checkout-session",auth,async(req,res)=>{if(!process.env.STRIPE_SECRET_KEY)return res.status(503).json({message:"Stripe n'est pas configuré sur le backend."});const o=db.orders.find(x=>x.id===req.body?.orderId&&(x.userId===req.user.id||req.user.isAdmin));if(!o)return res.status(404).json({message:"Commande introuvable."});try{const p=new URLSearchParams();p.set("mode","payment");p.set("success_url",String(req.body.successUrl||""));p.set("cancel_url",String(req.body.cancelUrl||""));p.set("line_items[0][quantity]","1");p.set("line_items[0][price_data][currency]",String(process.env.STRIPE_CURRENCY||"usd").toLowerCase());p.set("line_items[0][price_data][product_data][name]",`ZhuoMarket ${o.id}`);p.set("line_items[0][price_data][unit_amount]",String(Math.round(o.total*100)));const r=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${process.env.STRIPE_SECRET_KEY}`,"Content-Type":"application/x-www-form-urlencoded"},body:p}),d=await r.json();if(!r.ok)return res.status(502).json({message:d.error?.message||"Stripe error"});o.paymentSessionId=d.id;save();res.json({url:d.url,id:d.id})}catch(e){res.status(502).json({message:e.message})}});
app.get("/api/payments/stripe/session",auth,async(req,res)=>{if(!process.env.STRIPE_SECRET_KEY)return res.status(503).json({message:"Stripe n'est pas configuré."});const r=await fetch(`https://api.stripe.com/v1/checkout/sessions/${encodeURIComponent(String(req.query.id||""))}`,{headers:{Authorization:`Bearer ${process.env.STRIPE_SECRET_KEY}`}}),d=await r.json();if(!r.ok)return res.status(502).json({message:d.error?.message||"Stripe error"});res.json(d)});

// PayPal
async function paypalToken(){const base=String(process.env.PAYPAL_MODE||"sandbox").toLowerCase()==="live"?"https://api-m.paypal.com":"https://api-m.sandbox.paypal.com",authz=Buffer.from(`${process.env.PAYPAL_CLIENT_ID}:${process.env.PAYPAL_CLIENT_SECRET}`).toString("base64"),r=await fetch(`${base}/v1/oauth2/token`,{method:"POST",headers:{Authorization:`Basic ${authz}`,"Content-Type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials"}),d=await r.json();if(!r.ok)throw new Error(d.error_description||"PayPal auth error");return{token:d.access_token,base}}
app.post("/api/payments/paypal/create-order",auth,async(req,res)=>{if(!process.env.PAYPAL_CLIENT_ID||!process.env.PAYPAL_CLIENT_SECRET)return res.status(503).json({message:"PayPal n'est pas configuré."});const o=db.orders.find(x=>x.id===req.body?.orderId&&(x.userId===req.user.id||req.user.isAdmin));if(!o)return res.status(404).json({message:"Commande introuvable."});try{const{token,base}=await paypalToken(),r=await fetch(`${base}/v2/checkout/orders`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({intent:"CAPTURE",purchase_units:[{reference_id:o.id,amount:{currency_code:"USD",value:Math.max(0,o.total).toFixed(2)}}],application_context:{return_url:req.body.returnUrl,cancel_url:req.body.cancelUrl}})}),d=await r.json();if(!r.ok)return res.status(502).json({message:d.message||"PayPal error"});o.paypalOrderId=d.id;save();res.json({id:d.id,url:d.links?.find(x=>x.rel==="approve")?.href,links:d.links})}catch(e){res.status(502).json({message:e.message})}});
app.post("/api/payments/paypal/capture-order",auth,async(req,res)=>{if(!process.env.PAYPAL_CLIENT_ID||!process.env.PAYPAL_CLIENT_SECRET)return res.status(503).json({message:"PayPal n'est pas configuré."});const o=db.orders.find(x=>x.id===req.body?.orderId&&(x.userId===req.user.id||req.user.isAdmin));if(!o)return res.status(404).json({message:"Commande introuvable."});try{const{token,base}=await paypalToken(),pid=String(req.body.paypalOrderId||o.paypalOrderId||""),r=await fetch(`${base}/v2/checkout/orders/${encodeURIComponent(pid)}/capture`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"}}),d=await r.json();if(!r.ok)return res.status(502).json({message:d.message||"PayPal capture error"});o.paymentStatus="paid";o.status="processing";o.updatedAt=now();save();res.json({ok:true,order:o,paypal:d})}catch(e){res.status(502).json({message:e.message})}});

// Streaming
app.get("/api/streaming-plans",(_r,s)=>s.json({plans:{netflix:db.streamingPlans.filter(x=>x.service==="netflix"&&x.enabled!==false),disney:db.streamingPlans.filter(x=>x.service==="disney"&&x.enabled!==false)}}));
app.get("/api/admin/streaming-plans",auth,admin,(_r,s)=>s.json({plans:db.streamingPlans}));
app.post("/api/admin/streaming-plans",auth,admin,(req,res)=>{const b=req.body||{},p={id:id("sp_"),service:String(b.service||"netflix"),name:String(b.name||"Plan"),price:num(b.price),currency:String(b.currency||"HTG").toUpperCase()==="USD"?"USD":"HTG",description:String(b.description||"Abonnement mensuel"),enabled:b.enabled!==false};db.streamingPlans.push(p);save();res.status(201).json({plan:p})});
app.patch("/api/admin/streaming-plans/:id",auth,admin,(req,res)=>{const p=db.streamingPlans.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({message:"Plan introuvable."});Object.assign(p,req.body||{},{id:p.id});save();res.json({plan:p})});
app.delete("/api/admin/streaming-plans/:id",auth,admin,(req,res)=>{db.streamingPlans=db.streamingPlans.filter(x=>x.id!==req.params.id);save();res.json({ok:true})});

// Settings
app.get("/api/settings/trade",(_r,s)=>s.json({enabled:db.settings.tradeEnabled!==false}));app.patch("/api/admin/settings/trade",auth,admin,(req,res)=>{db.settings.tradeEnabled=req.body.enabled!==false;save();res.json({enabled:db.settings.tradeEnabled})});
app.get("/api/support/config",(_r,s)=>s.json({adminPhone:db.settings.adminPhone||process.env.ADMIN_WHATSAPP||"",whatsapp:db.settings.adminPhone||process.env.ADMIN_WHATSAPP||""}));
app.patch("/api/admin/settings/support",auth,admin,(req,res)=>{db.settings.adminPhone=String(req.body.adminPhone||"");save();res.json({adminPhone:db.settings.adminPhone})});

// Admin stats/users
app.get("/api/users",auth,admin,(_r,s)=>s.json({users:db.users.map(safe)}));app.get("/api/admin/users",auth,admin,(_r,s)=>s.json({users:db.users.map(safe)}));
app.get("/api/admin/stats",auth,admin,(_r,s)=>{const paid=db.orders.filter(o=>["paid","processing","completed","delivered"].includes(o.paymentStatus)||["processing","completed","delivered"].includes(o.status)),totalSales=paid.reduce((a,o)=>a+num(o.total),0),dailySales=[];for(let i=6;i>=0;i--){const k=new Date(Date.now()-i*86400000).toISOString().slice(0,10);dailySales.push({date:k,value:paid.filter(o=>String(o.createdAt).slice(0,10)===k).reduce((a,o)=>a+num(o.total),0)})}s.json({totalSales,revenue:totalSales,usersCount:db.users.filter(x=>!x.isAdmin).length,ordersCount:db.orders.length,productsCount:db.products.length,dailySales})});

// Admin messages/team
app.get("/api/admin/messages",auth,admin,(_r,s)=>{const conversations=db.conversations.map(c=>{const u=db.users.find(x=>x.id===c.userId)||{},m=db.messages.filter(x=>x.conversationId===c.id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),last=m[0];return{id:c.id,name:u.name||"Client",email:u.email||"",avatar:u.avatar||"",lastMessage:last?.message||"",lastMessageAt:last?.createdAt||c.updatedAt,unread:m.filter(x=>x.senderRole==="customer"&&!x.readByAdmin).length}}).sort((a,b)=>String(b.lastMessageAt).localeCompare(String(a.lastMessageAt)));s.json({conversations})});
app.get("/api/admin/messages/unread",auth,admin,(_r,s)=>s.json({unread:db.messages.filter(x=>x.senderRole==="customer"&&!x.readByAdmin).length,notifications:[]}));
app.get("/api/admin/messages/:id",auth,admin,(req,res)=>{const c=db.conversations.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({message:"Conversation introuvable."});const a=db.messages.filter(x=>x.conversationId===c.id).sort((x,y)=>String(x.createdAt).localeCompare(String(y.createdAt)));a.forEach(x=>{if(x.senderRole==="customer")x.readByAdmin=true});save();res.json({messages:a})});
app.post("/api/admin/messages/:id",auth,admin,(req,res)=>{const c=db.conversations.find(x=>x.id===req.params.id);if(!c)return res.status(404).json({message:"Conversation introuvable."});const m={id:id("msg_"),conversationId:c.id,userId:c.userId,senderId:req.user.id,senderRole:"admin",message:String(req.body.message||""),severity:"normal",urgent:false,createdAt:now(),readByAdmin:true};db.messages.push(m);c.updatedAt=now();db.notifications.push({id:id("not_"),userId:c.userId,type:"message",title:"Réponse du support",message:m.message,read:false,createdAt:now()});save();res.status(201).json({message:m})});
app.get("/api/admin/notifications",auth,admin,(_r,s)=>s.json({notifications:db.notifications.filter(x=>!x.userId)}));
app.get("/api/admin/team",auth,admin,(_r,s)=>s.json({admins:db.users.filter(x=>x.isAdmin).map(safe)}));
function teamKey(a,b){return[a,b].sort().join(":")}
app.get("/api/admin/team/chats",auth,admin,(req,res)=>sTeam(req,res));function sTeam(req,res){res.json({chats:db.users.filter(x=>x.isAdmin&&x.id!==req.user.id).map(x=>({id:x.id,name:x.name,email:x.email,role:x.role,avatar:x.avatar||""}))})}
app.get("/api/admin/team/chats/:peerId",auth,admin,(req,res)=>res.json({messages:db.messages.filter(x=>x.teamKey===teamKey(req.user.id,req.params.peerId)).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)))}));
app.post("/api/admin/team/chats/:peerId",auth,admin,(req,res)=>{const p=db.users.find(x=>x.id===req.params.peerId&&x.isAdmin);if(!p)return res.status(404).json({message:"Admin introuvable."});const m={id:id("tmsg_"),teamKey:teamKey(req.user.id,p.id),senderId:req.user.id,senderRole:"admin",message:String(req.body.message||""),createdAt:now()};db.messages.push(m);save();res.status(201).json({message:m})});

// Confirmation code
app.post("/api/admin/orders/:id/confirmation-code",auth,admin,(req,res)=>{const o=db.orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({message:"Commande introuvable."});const c=String(Math.floor(100000+Math.random()*900000));o.confirmationCode=c;o.confirmationCodeCreatedAt=now();save();res.json({code:c,confirmationCode:c,orderId:o.id})});

// Push subscription
app.get("/api/push/public-key",(_r,s)=>process.env.VAPID_PUBLIC_KEY?s.json({publicKey:process.env.VAPID_PUBLIC_KEY}):s.status(503).json({message:"Push non configuré."}));
app.post("/api/push/subscribe",auth,(req,res)=>{db.pushSubscriptions=db.pushSubscriptions.filter(x=>x.userId!==req.user.id||x.endpoint!==req.body.endpoint);db.pushSubscriptions.push({userId:req.user.id,...req.body,createdAt:now()});save();res.status(201).json({ok:true})});
app.delete("/api/push/subscribe",auth,(req,res)=>{db.pushSubscriptions=db.pushSubscriptions.filter(x=>x.userId!==req.user.id||x.endpoint!==req.body.endpoint);save();res.json({ok:true})});

app.use((err,_req,res,_next)=>{console.error(err);res.status(400).json({message:err?.message||"Erreur serveur."})});
(async()=>{await ensureAdmin();app.listen(PORT,()=>console.log(`ZhuoMarket backend listening on ${PORT}`))})();
